import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, EB_Garamond, Noto_Sans, IBM_Plex_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import PreventZoom from "@/components/PreventZoom";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
});

const cylburn = localFont({
  src: "../../public/fonts/Cylburn.ttf",
  variable: "--font-cylburn",
});

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const ibmSans = IBM_Plex_Sans({
  subsets: ["latin"],
  variable: "--font-ibm-sans",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#ffffff",
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover", 
    maximumScale: 1,       
  userScalable: false, 
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${ebGaramond.variable} ${cylburn.variable} ${notoSans.variable} ${ibmSans.variable}`}
    >
      <head>
        

        {/* Hero */}
        <link rel="preload" as="image" type="image/svg+xml" href="/images/Hero/BungaKiri.svg" />
        <link rel="preload" as="image" type="image/svg+xml" href="/images/Hero/AmplopKotak.svg" />
        <link rel="preload" as="image" type="image/svg+xml" href="/images/Hero/AmplopHD.svg" />
        <link rel="preload" as="image" type="image/svg+xml" href="/images/Hero/Pita.svg" />
        <link rel="preload" as="image" type="image/webp" href="/images/Hero/AmplopDouble.webp" />
        <link rel="preload" as="image" type="image/webp" href="/images/Hero/AmplopBunga.webp" />
        <link rel="preload" as="image" type="image/webp" href="/images/Hero/BungaHD.webp" />
        <link rel="preload" as="image" type="image/svg+xml" href="/images/Hero/FotoCew.svg" />
        <link rel="preload" as="image" type="image/svg+xml" href="/images/Hero/FotoCowo.svg" />
        <link rel="preload" as="image" type="image/webp" href="/images/Hero/Default.webp" />

        {/* Wishes */}
        <link rel="preload" as="image" href="/images/Wishes/BungaAtas.svg" />
        <link rel="preload" as="image" href="/images/Wishes/DaunAtas.webp" />
        <link rel="preload" as="image" href="/images/Wishes/DaunBawah.webp" />
        <link rel="preload" as="image" href="/images/Wishes/DaunKanan.webp" />
        <link rel="preload" as="image" href="/images/Wishes/BungaKiri.svg" />
        <link rel="preload" as="image" href="/images/Wishes/BungaKanan.svg" />
        <link rel="preload" as="image" href="/images/Wishes/BungaKananBawah.webp" />
        <link rel="preload" as="image" href="/images/Wishes/BungaKiriBawah.webp" />


      </head>


      <body>
          <PreventZoom />
          {children}
      </body>
    </html>
  );
}